version: '3.8'

services:
  apibridge:
    build: .
    ports:
      - "5566:5566"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      # 添加其他环境变量
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - SNOVA_API_KEY=${SNOVA_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
    # 如果你需要健康检查
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:5566/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

# 如果你的应用需要一个数据库，你可以取消注释以下部分
#
# db:
#   image: postgres:13
#   environment:
#     - POSTGRES_DB=apibridge
#     - POSTGRES_USER=apibridge
#     - POSTGRES_PASSWORD=your_password
#   volumes:
#     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
